# Generic (Opaque) Secret
# Values must be base64 encoded in the 'data' field
# OR use 'stringData' for plain text (Kubernetes encodes it for you)
# Apply: kubectl apply -f 02-secret-generic.yaml
# Decode: kubectl get secret aaik-secret -o jsonpath='{.data.DB_PASSWORD}' | base64 -d

apiVersion: v1
kind: Secret
metadata:
  name: aaik-secret
type: Opaque
stringData:                     # plain text — Kubernetes base64-encodes automatically
  DB_PASSWORD: "mysupersecretpassword"
  API_KEY: "aaik-api-key-12345"
  DB_HOST: "postgres.default.svc.cluster.local"
