# Ingress with multiple path-based routes
# Apply: kubectl apply -f 02-ingress-multi-path.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aaik-multi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: aaik.example.com
    http:
      paths:
      - path: /app(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: aaik-clusterip
            port:
              number: 80
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: aaik-api-svc
            port:
              number: 8080
